### ISSUE TITLE
Plugin locks up

### ISSUE THREAD

**Issue by Celuni** [Queuete/SimpleStashie#3]
Holding down/repressing the hotkey until there is no loot in your inventory will make the plugin stop working.

Fix:
```
public override void Render()
        {
            if (!IsRunConditionMet()) return;
            IsRunning = true;

            var coroutineWorker = new Coroutine(StashItems(), this, "SimpleStashie.StashItems");
            IsRunning = !Core.ParallelRunner.Run( coroutineWorker ).IsDone; // Incase the Coroutine finished and IsRunning = false will never be called
        }
````

**Comment by Queuete** [comment]
Hello there,
Thanks for your report. Why would you want to hold down the hotkey? Pressing it once starts the process which empties your inventory. 
The whole coroutine behavior will vanish in the next bigger hud patch. The "IsRunning" flag should be redundant by then, because the Job will only be executed when the last Job with the same name is completed.

I'll keep this ticket open till the patch hits, as a reminder to check wether this behavour is really gone.
